const now = new Date();
const iso = (days = 0, hours = 0) => {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  d.setHours(d.getHours() - hours);
  return d.toISOString();
};

const makeId = (prefix) => `${prefix}_${Math.random().toString(36).slice(2, 10)}`;

export function createInitialState() {
  return {
    meta: {
      version: 1,
      createdAt: now.toISOString(),
    },
    ui: {
      view: 'dashboard',
      selectedClientId: 'c1',
      selectedTaskId: 't2',
      selectedProductId: 'p2',
      filters: {
        clientQuery: '',
        messageQuery: '',
        taskQuery: '',
        clientStatus: 'all',
        clientChannel: 'all',
        inboxChannel: 'all',
        taskFilter: 'all',
        productQuery: '',
        knowledgeRole: 'all',
      },
      composer: {
        channel: 'Telegram',
        text: '',
      },
      quickTest: null,
      loginCodeHint: '246810',
      adminImportDraft: 'login,name,role,email,active\nnew.sales,Ольга Ким,front,olga@plants.local,true',
    },
    security: {
      sessionIp: `10.4.${Math.floor(Math.random() * 180) + 10}.${Math.floor(Math.random() * 200) + 10}`,
      inactivityMinutes: 0,
      blocked: false,
      blockReason: '',
      openEvents: {},
      lastActivityAt: now.toISOString(),
    },
    auth: {
      userId: null,
      pendingCode: '246810',
      codeIssuedAt: now.toISOString(),
      lastLoginAt: null,
    },
    users: [
      {
        id: 'u-admin',
        login: 'admin',
        password: 'admin123',
        name: 'Алина Морозова',
        role: 'admin',
        email: 'admin@plants.local',
        active: true,
        schedule: '09:00-18:00',
      },
      {
        id: 'u-front',
        login: 'front',
        password: 'front123',
        name: 'Мария Лебедева',
        role: 'front',
        email: 'maria@plants.local',
        active: true,
        schedule: '10:00-19:00',
      },
      {
        id: 'u-hybrid',
        login: 'hybrid',
        password: 'hybrid123',
        name: 'Илья Котов',
        role: 'hybrid',
        email: 'ilya@plants.local',
        active: true,
        schedule: '09:30-18:30',
      },
      {
        id: 'u-back',
        login: 'back',
        password: 'back123',
        name: 'Сергей Орлов',
        role: 'back',
        email: 'sergey@plants.local',
        active: true,
        schedule: '08:00-17:00',
      },
      {
        id: 'u-content',
        login: 'content',
        password: 'content123',
        name: 'Екатерина Сахарова',
        role: 'content',
        email: 'katya@plants.local',
        active: true,
        schedule: '11:00-20:00',
      },
      {
        id: 'u-locomotive',
        login: 'locomotive',
        password: 'drive123',
        name: 'Денис Сорокин',
        role: 'locomotive',
        email: 'denis@plants.local',
        active: true,
        schedule: '08:30-17:30',
      },
    ],
    roles: {
      admin: ['dashboard', 'inbox', 'clients', 'tasks', 'products', 'knowledge', 'analytics', 'admin'],
      front: ['dashboard', 'inbox', 'clients', 'tasks', 'knowledge', 'analytics'],
      back: ['dashboard', 'tasks', 'products', 'knowledge', 'analytics'],
      hybrid: ['dashboard', 'inbox', 'clients', 'tasks', 'products', 'knowledge', 'analytics'],
      content: ['dashboard', 'inbox', 'knowledge', 'analytics'],
      locomotive: ['dashboard', 'tasks', 'products', 'analytics', 'knowledge'],
    },
    dictionaries: {
      sources: ['Telegram', 'VK', 'WhatsApp', 'Email', 'Сайт', 'Flowwow', 'Авито', '1С', 'Банк'],
      tags: ['орхидеи', 'суккуленты', 'доставка', 'опт', 'подарок', 'корпоратив', 'самовывоз', 'VIP'],
      interests: ['Комнатные растения', 'Букеты', 'Срезка', 'Суккуленты', 'Горшки', 'Удобрения'],
      statuses: ['Нераспознанный', 'Лид', 'Покупатель'],
      taskStatuses: ['new', 'in_progress', 'waiting', 'done'],
    },
    channels: ['Telegram', 'VK', 'WhatsApp', 'Email', 'Сайт', 'Flowwow', 'Авито'],
    messages: [
      {
        id: makeId('m'),
        channel: 'Telegram',
        direction: 'in',
        contact: '+79990000001',
        clientId: 'c1',
        author: 'Елена',
        text: 'Здравствуйте! Подскажите, есть ли фикус лирата в наличии?',
        createdAt: iso(0, 1),
        unread: true,
        assignedTo: 'u-front',
      },
      {
        id: makeId('m'),
        channel: 'VK',
        direction: 'in',
        contact: 'vk.com/andrey',
        clientId: 'c3',
        author: 'Андрей',
        text: 'Ищу подарок для офиса. Что посоветуете до 5000?',
        createdAt: iso(0, 2),
        unread: true,
        assignedTo: 'u-front',
      },
      {
        id: makeId('m'),
        channel: 'WhatsApp',
        direction: 'out',
        contact: '+79990000005',
        clientId: 'c5',
        author: 'Менеджер',
        text: 'Напоминаю про доставку сегодня с 18:00 до 20:00.',
        createdAt: iso(0, 5),
        unread: false,
        assignedTo: 'u-hybrid',
      },
      {
        id: makeId('m'),
        channel: 'Email',
        direction: 'in',
        contact: 'anton@company.ru',
        clientId: 'c4',
        author: 'Антон',
        text: 'Пришлите, пожалуйста, КП на 24 растения для ресепшн.',
        createdAt: iso(1, 0),
        unread: true,
        assignedTo: 'u-content',
      },
      {
        id: makeId('m'),
        channel: 'Авито',
        direction: 'in',
        contact: 'avito:green-loft',
        clientId: 'c6',
        author: 'Марина',
        text: 'Работаете ли в выходные и как добраться до магазина?',
        createdAt: iso(1, 3),
        unread: true,
        assignedTo: 'u-front',
      },
      {
        id: makeId('m'),
        channel: 'Сайт',
        direction: 'in',
        contact: 'site:form-19',
        clientId: 'c2',
        author: 'Светлана',
        text: 'Нужен уход за орхидеей и доставка завтра утром.',
        createdAt: iso(2, 2),
        unread: false,
        assignedTo: 'u-front',
      },
    ],
    clients: [
      {
        id: 'c1',
        name: 'Елена Иванова',
        phone: '+79990000001',
        email: 'elena@example.com',
        oneCId: '1C-1001',
        source: 'Telegram',
        preferredChannel: 'Telegram',
        statusHint: 'Покупатель',
        tags: ['доставка', 'орхидеи'],
        interests: ['Комнатные растения', 'Суккуленты'],
        discountCards: ['VIP-12'],
        wishList: ['Фикус Лирата', 'Монстера Адансона'],
        waitList: ['Фикус Лирата'],
        notesInternal: 'Зеленый список. Любит быструю доставку.',
        quality: 'A',
        blacklist: false,
        greenList: true,
        history: [
          { type: 'purchase', text: 'Покупка на 8 900 ₽ через 1С', at: iso(6, 0) },
          { type: 'message', text: 'Запрос на фикус лирата', at: iso(0, 1) },
        ],
        purchases: [
          { source: '1С', amount: 8900, at: iso(6, 0) },
          { source: 'Банк', amount: 4200, at: iso(11, 0) },
        ],
        bankPurchases: [
          { amount: 4200, at: iso(11, 0), matched: true },
        ],
        channelHistory: ['Telegram', 'WhatsApp'],
        createdAt: iso(34, 0),
        updatedAt: iso(0, 1),
      },
      {
        id: 'c2',
        name: 'Светлана Кравцова',
        phone: '+79990000002',
        email: 'svetlana@example.com',
        oneCId: '1C-1002',
        source: 'Сайт',
        preferredChannel: 'Email',
        statusHint: 'Лид',
        tags: ['орхидеи'],
        interests: ['Орхидеи', 'Удобрения'],
        discountCards: [],
        wishList: ['Орхидея Фаленопсис'],
        waitList: ['Орхидея Фаленопсис'],
        notesInternal: 'Качество лида: теплый. Перезвонить после обеда.',
        quality: 'B',
        blacklist: false,
        greenList: false,
        history: [
          { type: 'message', text: 'Задала вопрос по уходу за орхидеей', at: iso(2, 2) },
        ],
        purchases: [],
        bankPurchases: [],
        channelHistory: ['Сайт', 'Email'],
        createdAt: iso(11, 4),
        updatedAt: iso(2, 2),
      },
      {
        id: 'c3',
        name: 'Андрей Мельников',
        phone: '+79990000003',
        email: 'andrey@studio.ru',
        oneCId: '1C-1003',
        source: 'VK',
        preferredChannel: 'VK',
        statusHint: 'Лид',
        tags: ['подарок', 'корпоратив'],
        interests: ['Комнатные растения', 'Горшки'],
        discountCards: ['STUDIO-5'],
        wishList: ['Фикус Бенджамина', 'Кактус микс'],
        waitList: ['Фикус Бенджамина'],
        notesInternal: 'Можно апсейл на уход и кашпо.',
        quality: 'A',
        blacklist: false,
        greenList: true,
        history: [
          { type: 'message', text: 'Ищет подарок для офиса до 5000 ₽', at: iso(0, 2) },
        ],
        purchases: [],
        bankPurchases: [],
        channelHistory: ['VK'],
        createdAt: iso(8, 5),
        updatedAt: iso(0, 2),
      },
      {
        id: 'c4',
        name: 'Антон Сергеев',
        phone: '+79990000004',
        email: 'anton@company.ru',
        oneCId: '1C-1004',
        source: 'Email',
        preferredChannel: 'Email',
        statusHint: 'Покупатель',
        tags: ['корпоратив'],
        interests: ['Комнатные растения', 'Букеты'],
        discountCards: ['CORP-20'],
        wishList: ['Фиттония', 'Сансевиерия'],
        waitList: [],
        notesInternal: 'Считать как опт. Нужен счет и КП.',
        quality: 'A',
        blacklist: false,
        greenList: true,
        history: [
          { type: 'purchase', text: 'Счет и поставка на 38 000 ₽', at: iso(9, 3) },
          { type: 'message', text: 'Запросил КП', at: iso(1, 0) },
        ],
        purchases: [{ source: '1С', amount: 38000, at: iso(9, 3) }],
        bankPurchases: [],
        channelHistory: ['Email'],
        createdAt: iso(23, 0),
        updatedAt: iso(1, 0),
      },
      {
        id: 'c5',
        name: 'Марина Белова',
        phone: '+79990000005',
        email: 'marina@example.com',
        oneCId: '',
        source: 'Авито',
        preferredChannel: 'WhatsApp',
        statusHint: 'Покупатель',
        tags: ['самовывоз'],
        interests: ['Суккуленты', 'Горшки'],
        discountCards: [],
        wishList: ['Алоэ вера'],
        waitList: [],
        notesInternal: 'Проверить адрес самовывоза.',
        quality: 'B',
        blacklist: false,
        greenList: false,
        history: [
          { type: 'purchase', text: 'Неподтвержденная покупка через банк', at: iso(4, 0) },
        ],
        purchases: [],
        bankPurchases: [{ amount: 2400, at: iso(4, 0), matched: false }],
        channelHistory: ['Авито', 'WhatsApp'],
        createdAt: iso(13, 0),
        updatedAt: iso(4, 0),
      },
      {
        id: 'c6',
        name: 'Новый контакт',
        phone: '',
        email: 'unknown@vk.local',
        oneCId: '',
        source: 'VK',
        preferredChannel: 'VK',
        statusHint: 'Нераспознанный',
        tags: [],
        interests: [],
        discountCards: [],
        wishList: ['Композиция для стойки'],
        waitList: ['Композиция для стойки'],
        notesInternal: '',
        quality: 'C',
        blacklist: false,
        greenList: false,
        history: [
          { type: 'message', text: 'Новый контакт без телефона', at: iso(1, 3) },
        ],
        purchases: [],
        bankPurchases: [],
        channelHistory: ['VK'],
        createdAt: iso(1, 3),
        updatedAt: iso(1, 3),
      },
      {
        id: 'c7',
        name: 'Дарья Самойлова',
        phone: '+79990000007',
        email: 'dasha@example.com',
        oneCId: '1C-1012',
        source: 'Flowwow',
        preferredChannel: 'Telegram',
        statusHint: 'Покупатель',
        tags: ['подарок', 'VIP'],
        interests: ['Букеты', 'Комнатные растения'],
        discountCards: ['VIP-33'],
        wishList: ['Пионовидные розы'],
        waitList: [],
        notesInternal: 'Очень быстрые ответы, любит фото и видео.',
        quality: 'A',
        blacklist: false,
        greenList: true,
        history: [
          { type: 'purchase', text: 'Регулярные покупки через Flowwow', at: iso(3, 2) },
        ],
        purchases: [{ source: '1С', amount: 12600, at: iso(3, 2) }],
        bankPurchases: [],
        channelHistory: ['Flowwow', 'Telegram'],
        createdAt: iso(15, 0),
        updatedAt: iso(3, 2),
      },
      {
        id: 'c8',
        name: 'Иван Глушков',
        phone: '+79990000008',
        email: 'ivan@local.ru',
        oneCId: '',
        source: 'Банк',
        preferredChannel: 'Email',
        statusHint: 'Лид',
        tags: ['опт'],
        interests: ['Горшки', 'Удобрения'],
        discountCards: ['B2B-7'],
        wishList: ['Горшки керам. 20 шт'],
        waitList: ['Горшки керам. 20 шт'],
        notesInternal: 'Черный список не ставить. Долго принимает решение.',
        quality: 'B',
        blacklist: false,
        greenList: false,
        history: [
          { type: 'message', text: 'Запрос на оптовый заказ из банка', at: iso(7, 0) },
        ],
        purchases: [],
        bankPurchases: [{ amount: 17500, at: iso(7, 0), matched: false }],
        channelHistory: ['Email'],
        createdAt: iso(20, 0),
        updatedAt: iso(7, 0),
      },
    ],
    tasks: [
      {
        id: 't1',
        title: 'Срочный ответ по остаткам фикуса лирата',
        priority: 1,
        urgency: 'urgent',
        dueAt: iso(0, 0.25),
        status: 'new',
        origin: 'От руководства',
        assignedTo: 'u-front',
        clientId: 'c1',
        comments: [{ author: 'Руководитель', text: 'Нужен ответ до 12:30.', at: iso(0, 0.3) }],
        createdAt: iso(0, 0.3),
      },
      {
        id: 't2',
        title: 'Ответить на ночную заявку от Flowwow',
        priority: 3,
        urgency: 'normal',
        dueAt: iso(0, 1),
        status: 'in_progress',
        origin: 'Клиенты',
        assignedTo: 'u-hybrid',
        clientId: 'c7',
        comments: [{ author: 'Мария', text: 'Взято в работу.', at: iso(0, 1) }],
        createdAt: iso(0, 1),
      },
      {
        id: 't3',
        title: 'Сверка остатков и лист "Ушедшего в производство"',
        priority: 4,
        urgency: 'system',
        dueAt: iso(0, 3),
        status: 'waiting',
        origin: 'Системные',
        assignedTo: 'u-back',
        clientId: null,
        comments: [],
        createdAt: iso(0, 3),
      },
      {
        id: 't4',
        title: 'КП для корпоративного клиента Антона Сергева',
        priority: 2,
        urgency: 'normal',
        dueAt: iso(1, 0),
        status: 'new',
        origin: 'Внутренние',
        assignedTo: 'u-content',
        clientId: 'c4',
        comments: [],
        createdAt: iso(1, 0),
      },
      {
        id: 't5',
        title: 'Авто follow-up по клиентам без ответа 48 часов',
        priority: 4,
        urgency: 'system',
        dueAt: iso(0, 2),
        status: 'done',
        origin: 'Системные',
        assignedTo: 'u-locomotive',
        clientId: 'c2',
        comments: [{ author: 'CRM', text: 'Напоминание отправлено.', at: iso(0, 2) }],
        createdAt: iso(0, 2),
      },
      {
        id: 't6',
        title: 'Передать заявку по самовывозу в магазин',
        priority: 2,
        urgency: 'normal',
        dueAt: iso(0, 0.5),
        status: 'new',
        origin: 'Внутренние',
        assignedTo: 'u-front',
        clientId: 'c5',
        comments: [],
        createdAt: iso(0, 0.5),
      },
    ],
    products: [
      {
        id: 'p1',
        name: 'Фикус Лирата',
        parent: 'Комнатные растения',
        sku: 'PL-001',
        type: 'plant',
        stock: 4,
        reserve: 2,
        price: 5890,
        inProduction: 1,
        status: 'low',
        updatedAt: iso(0, 0.1),
      },
      {
        id: 'p2',
        name: 'Монстера Адансона',
        parent: 'Комнатные растения',
        sku: 'PL-002',
        type: 'plant',
        stock: 10,
        reserve: 1,
        price: 3190,
        inProduction: 0,
        status: 'ok',
        updatedAt: iso(0, 0.2),
      },
      {
        id: 'p3',
        name: 'Орхидея Фаленопсис',
        parent: 'Комнатные растения',
        sku: 'PL-003',
        type: 'plant',
        stock: 2,
        reserve: 1,
        price: 2290,
        inProduction: 2,
        status: 'critical',
        updatedAt: iso(0, 0.05),
      },
      {
        id: 'p4',
        name: 'Керамический горшок 20 см',
        parent: 'Горшки и кашпо',
        sku: 'AC-010',
        type: 'other',
        stock: 28,
        reserve: 6,
        price: 890,
        inProduction: 4,
        status: 'ok',
        updatedAt: iso(0, 0.05),
      },
      {
        id: 'p5',
        name: 'Удобрение универсальное',
        parent: 'Удобрения',
        sku: 'AC-011',
        type: 'other',
        stock: 18,
        reserve: 3,
        price: 520,
        inProduction: 0,
        status: 'ok',
        updatedAt: iso(0, 0.05),
      },
      {
        id: 'p6',
        name: 'Букет "Весенний ветер"',
        parent: 'Букеты',
        sku: 'BK-022',
        type: 'other',
        stock: 6,
        reserve: 1,
        price: 2790,
        inProduction: 2,
        status: 'low',
        updatedAt: iso(0, 0.05),
      },
    ],
    knowledge: [
      {
        id: 'k1',
        title: 'Стандарт ответа по наличию',
        role: 'front',
        body: 'Сначала проверяем остаток в 1С, затем даем краткий ответ, предлагая альтернативу и время доставки.',
      },
      {
        id: 'k2',
        title: 'Скрипт для отсутствующего товара',
        role: 'hybrid',
        body: 'Если товара нет, уточняем срочность, предлагаем под заказ и ставим follow-up через 24 часа.',
      },
      {
        id: 'k3',
        title: 'Корпоративный КП',
        role: 'content',
        body: 'Используем шаблон с ассортиментом, сроками, условиями оплаты и фото-референсами.',
      },
      {
        id: 'k4',
        title: 'Приемка из 1С',
        role: 'back',
        body: 'После импорта проверяем расхождения по остаткам, себестоимости и листу производства.',
      },
      {
        id: 'k5',
        title: 'Чат-бот выходного дня',
        role: 'locomotive',
        body: 'Сообщает адрес, график и предлагает оставить контакт для обратной связи в рабочее время.',
      },
      {
        id: 'k6',
        title: 'Режим "Быстрый тест"',
        role: 'admin',
        body: 'Администратор может заблокировать экран для мини-теста по ассортименту или стандартам сервиса.',
      },
    ],
    scripts: [
      {
        id: 's1',
        trigger: 'налич',
        title: 'Проверка наличия',
        answerTemplate: 'Есть {stock} шт. / Доступно под заказ.',
      },
      {
        id: 's2',
        trigger: 'доставка',
        title: 'Информация по доставке',
        answerTemplate: 'Доставка сегодня до 20:00, самовывоз доступен до 19:00.',
      },
      {
        id: 's3',
        trigger: 'адрес',
        title: 'График и адрес',
        answerTemplate: 'Мы находимся: Москва, ул. Листовая, 17. Работаем ежедневно с 9:00 до 21:00.',
      },
    ],
    analytics: {
      revenueByDay: [
        { day: 'Пн', value: 56000 },
        { day: 'Вт', value: 61000 },
        { day: 'Ср', value: 74000 },
        { day: 'Чт', value: 92000 },
        { day: 'Пт', value: 84000 },
        { day: 'Сб', value: 109000 },
        { day: 'Вс', value: 78000 },
      ],
      channelStats: [
        { label: 'Telegram', value: 38 },
        { label: 'VK', value: 24 },
        { label: 'WhatsApp', value: 31 },
        { label: 'Email', value: 19 },
        { label: 'Сайт', value: 27 },
        { label: 'Авито', value: 14 },
      ],
      employeeKpi: [
        { name: 'Мария', replies: 68, conversion: 0.31, speed: 4.2 },
        { name: 'Илья', replies: 54, conversion: 0.27, speed: 5.4 },
        { name: 'Екатерина', replies: 33, conversion: 0.22, speed: 6.8 },
        { name: 'Сергей', replies: 29, conversion: 0.18, speed: 7.1 },
      ],
      productTrend: [
        { label: 'Фикус Лирата', value: 4 },
        { label: 'Орхидея Фаленопсис', value: 2 },
        { label: 'Монстера', value: 10 },
        { label: 'Горшки', value: 28 },
      ],
    },
    news: [
      { id: makeId('n'), title: 'Импорт 1С обновлен', body: 'Новая синхронизация остатков и продаж проходит каждые 15 минут.', at: iso(0, 2) },
      { id: makeId('n'), title: 'Запущен бот выходного дня', body: 'Авито и VK отвечают по графику и адресу магазина.', at: iso(1, 2) },
      { id: makeId('n'), title: 'Добавлен быстрый тест', body: 'Администратор может блокировать рабочий экран для мини-экзамена.', at: iso(2, 1) },
    ],
    audit: [
      { id: makeId('a'), actor: 'CRM', ip: '127.0.0.1', action: 'Seed data loaded', before: 'empty', after: 'initial workspace populated', at: iso(0, 0.01) },
    ],
    notifications: [
      { id: makeId('t'), title: 'Добро пожаловать', text: 'Система готова к работе в демо-режиме.', type: 'info', at: iso(0, 0.01) },
    ],
  };
}
