# Generated by Django 6.0.6 on 2026-06-20 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=255)),
                ('before', models.TextField(blank=True)),
                ('after', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('one_c_id', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('preferred_channel', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('buyer', 'Покупатель'), ('lead', 'Лид'), ('unknown', 'Нераспознанный')], default='lead', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('discount_cards', models.JSONField(blank=True, default=list)),
                ('wish_list', models.JSONField(blank=True, default=list)),
                ('wait_list', models.JSONField(blank=True, default=list)),
                ('purchases', models.JSONField(blank=True, default=list)),
                ('bank_purchases', models.JSONField(blank=True, default=list)),
                ('internal_note', models.TextField(blank=True)),
                ('quality', models.CharField(blank=True, default='B', max_length=8)),
                ('black_list', models.BooleanField(default=False)),
                ('green_list', models.BooleanField(default=False)),
                ('history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['role', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('plant', 'Комнатное растение'), ('other', 'Прочее')], default='plant', max_length=16)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reserve', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_production', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'В норме'), ('low', 'Низкий'), ('critical', 'Критический')], default='ok', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['parent', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('front', 'Фронт'), ('back', 'Бек'), ('hybrid', 'Гибрид'), ('content', 'Контент'), ('locomotive', 'Локомотив'), ('admin', 'Администратор')], default='front', max_length=32)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('access_code', models.CharField(blank=True, max_length=16)),
                ('schedule', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('in', 'Входящее'), ('out', 'Исходящее')], max_length=8)),
                ('author_name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('unread', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4')], default=3)),
                ('urgency', models.CharField(default='normal', max_length=32)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('waiting', 'Ожидание'), ('done', 'Готово')], default='new', max_length=16)),
                ('origin', models.CharField(choices=[('От руководства', 'От руководства'), ('Внутренние', 'Внутренние'), ('Клиенты', 'Клиенты'), ('Системные', 'Системные')], default='Внутренние', max_length=64)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.client')),
            ],
            options={
                'ordering': ['priority', 'due_at', '-created_at'],
            },
        ),
    ]
