# Generated by Django 6.0.6 on 2026-06-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employeeprofile_last_activity_dictionaryentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list, help_text='Список {name, sku, qty, price}')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('assembled', 'Собран'), ('shipped', 'Отправлен'), ('delivered', 'Завершён'), ('cancelled', 'Отменён')], default='new', max_length=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
