# Generated by Django 6.0.6 on 2026-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_scriptrule_clockevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday_start', models.TimeField(default='09:00')),
                ('workday_end', models.TimeField(default='21:00')),
                ('weekend_start', models.TimeField(default='10:00')),
                ('weekend_end', models.TimeField(default='18:00')),
                ('address', models.CharField(blank=True, help_text='Адрес магазина', max_length=512)),
                ('message_template', models.TextField(default='Здравствуйте! Сейчас магазин не работает.\nГрафик работы:\nБудни: {workday_start} – {workday_end}\nВыходные: {weekend_start} – {weekend_end}\nНаш адрес: {address}\nОставьте сообщение — мы ответим в рабочее время.', help_text='{workday_start}, {workday_end}, {weekend_start}, {weekend_end}, {address} — подставляются автоматически')),
            ],
            options={
                'verbose_name': 'Настройки расписания',
                'verbose_name_plural': 'Настройки расписания',
            },
        ),
    ]
