# Generated by Django 6.0.6 on 2026-07-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_integrationevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_news_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('front', 'Фронт'), ('back', 'Бек'), ('hybrid', 'Гибрид'), ('content', 'Контент'), ('locomotive', 'Локомотив'), ('admin', 'Администратор')], max_length=32)),
                ('resource', models.CharField(choices=[('dashboard', 'Дашборд'), ('inbox', 'Единое окно'), ('clients', 'Клиенты'), ('tasks', 'Тикеты'), ('products', 'Склад'), ('knowledge', 'Обучение'), ('analytics', 'Аналитика'), ('admin', 'Админка'), ('users', 'Пользователи'), ('orders', 'Заказы'), ('messages', 'Сообщения'), ('dictionaries', 'Словари'), ('files', 'Файлы'), ('scripts', 'Скрипты'), ('schedule', 'График'), ('audit', 'Аудит'), ('fraud', 'Антифрод')], max_length=32)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'resource'],
                'unique_together': {('role', 'resource')},
            },
        ),
    ]
