# Generated by Django 6.0.6 on 2026-07-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_normalize_phone_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesettings',
            name='auto_reply_emergency_disabled',
            field=models.BooleanField(default=False, help_text='Полностью отключает автоответ на всех каналах. Сбор сообщений при этом продолжается.'),
        ),
    ]
