# Generated by Django 6.0.6 on 2026-07-03 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_schedulesettings_auto_reply_emergency_disabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesettings',
            name='auto_reply_emergency_disabled',
            field=models.BooleanField(default=False, help_text='Полностью отключает автоответ на всех каналах. Сбор сообщений при этом продолжается.', verbose_name='Аварийно отключить автоответ'),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.CharField(choices=[('front', 'Фронт'), ('back', 'Бек'), ('hybrid', 'Гибрид'), ('content', 'Контент'), ('locomotive', 'Локомотив'), ('admin', 'Администратор')], max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'role'],
                'unique_together': {('date', 'employee', 'role')},
            },
        ),
    ]
