# Generated by Django 6.0.6 on 2026-07-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_schedulesettings_auto_reply_emergency_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wish_products',
            field=models.ManyToManyField(blank=True, related_name='wishers', to='crm.product'),
        ),
    ]
