# Generated by Django 6.0.6 on 2026-07-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_normalize_phone_no_plus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Не запущен'), ('waiting', 'Ждём скан QR'), ('password_required', 'Нужен пароль 2FA'), ('success', 'Успешно'), ('error', 'Ошибка'), ('expired', 'Истекло время ожидания')], default='idle', max_length=20)),
                ('qr_data_uri', models.TextField(blank=True, default='')),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('pending_password', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QR-логин Telegram',
                'verbose_name_plural': 'QR-логин Telegram',
            },
        ),
    ]
